//! Private Git-over-SSH access for future authenticated API handlers.
use std::{
    collections::HashMap,
    io,
    path::{Path, PathBuf},
    sync::Arc,
    time::Duration,
};
use tokio::{process::Command, sync::Mutex};

#[derive(Clone)]
pub struct SshIdentity {
    pub private_key_path: PathBuf,
    pub known_hosts_path: PathBuf,
}

#[derive(Clone)]
pub struct GitClient {
    pub ssh_identity: SshIdentity,
    repository_root: PathBuf,
    port: u16,
    repository_locks: Arc<Mutex<HashMap<i32, Arc<Mutex<()>>>>>,
}

#[derive(Debug, PartialEq, Eq, serde::Serialize)]
pub struct GitRef {
    pub commit_sha: String,
    pub name: String,
}

impl GitClient {
    /// Keys are generated by setup, never generated or rotated during API startup.
    pub fn from_env() -> io::Result<Self> {
        let storage = std::env::var_os("GIT_STORAGE_DIR")
            .map(PathBuf::from)
            .unwrap_or_else(|| Path::new(env!("CARGO_MANIFEST_DIR")).join("../storage/git"));
        let port = std::env::var("GIT_SSH_PORT")
            .unwrap_or_else(|_| "2222".to_owned())
            .parse::<u16>()
            .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "Invalid GIT_SSH_PORT"))?;
        Self::configured(storage, port)
    }

    fn configured(storage: PathBuf, port: u16) -> io::Result<Self> {
        if !storage.is_absolute() || port < 1024 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "GIT_STORAGE_DIR must be absolute and GIT_SSH_PORT must be at least 1024",
            ));
        }
        reject_symlinks(&storage)?;
        let identity = SshIdentity {
            private_key_path: storage.join("ssh/client/id_ed25519"),
            known_hosts_path: storage.join("ssh/client/known_hosts"),
        };
        for path in [&identity.private_key_path, &identity.known_hosts_path] {
            reject_symlinks(path)?;
            let metadata = path.metadata().map_err(|error| {
                io::Error::new(
                    error.kind(),
                    "Git SSH identity is missing; run python3 git-server/scripts/setup_server.py",
                )
            })?;
            if !metadata.is_file() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "Git SSH identity must be a regular file",
                ));
            }
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                if metadata.permissions().mode() & 0o077 != 0 {
                    return Err(io::Error::new(
                        io::ErrorKind::PermissionDenied,
                        "Git SSH identity files must have permissions 0600",
                    ));
                }
            }
        }
        let repository_root = storage.join("projects");
        reject_symlinks(&repository_root)?;
        if !repository_root.is_dir() {
            return Err(io::Error::new(
                io::ErrorKind::NotFound,
                "Git repository root is missing; run Git server setup",
            ));
        }
        Ok(Self {
            ssh_identity: identity,
            repository_root: repository_root.canonicalize()?,
            port,
            repository_locks: Arc::new(Mutex::new(HashMap::new())),
        })
    }

    pub fn repository_root(&self) -> &Path {
        &self.repository_root
    }

    pub fn remote_url(&self, project_id: i32) -> io::Result<String> {
        validate_project_id(project_id)?;
        Ok(format!(
            "ssh://git@127.0.0.1:{}/repositories/{project_id}.git",
            self.port
        ))
    }

    /// Create local storage; the SSH service sees the same directory via a bind mount.
    /// Callers must first authorize access to the database project.
    pub async fn create_project_repository(&self, project_id: i32) -> io::Result<PathBuf> {
        validate_project_id(project_id)?;
        let lock = self
            .repository_locks
            .lock()
            .await
            .entry(project_id)
            .or_insert_with(|| Arc::new(Mutex::new(())))
            .clone();
        let _guard = lock.lock().await;
        let repository = self.repository_root.join(format!("{project_id}.git"));
        reject_symlinks(&repository)?;
        if !repository.exists() {
            #[cfg(unix)]
            {
                use std::os::unix::fs::DirBuilderExt;
                std::fs::DirBuilder::new().mode(0o700).create(&repository)?;
            }
            #[cfg(not(unix))]
            std::fs::create_dir(&repository)?;
        }
        if !repository.join("HEAD").exists() {
            let mut command = self.command();
            command
                .args([
                    "init",
                    "--bare",
                    "--quiet",
                    "--template=",
                    "--object-format=sha1",
                ])
                .arg(&repository);
            run(command).await?;
        }
        let mut command = self.command();
        command
            .arg("--git-dir")
            .arg(&repository)
            .args(["rev-parse", "--is-bare-repository"]);
        if run(command).await?.as_slice() != b"true\n" {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "Project storage must be a bare Git repository",
            ));
        }
        Ok(repository)
    }

    /// Ask the SSH server for permanently retained snapshots, without cloning.
    pub async fn list_snapshot_refs(&self, project_id: i32) -> io::Result<Vec<GitRef>> {
        let mut command = self.command();
        command
            .args(["ls-remote", "--refs"])
            .arg(self.remote_url(project_id)?)
            .arg("refs/snapshots/*");
        let output = run(command).await?;
        let output = String::from_utf8(output).map_err(|_| {
            io::Error::new(io::ErrorKind::InvalidData, "Invalid Git reference output")
        })?;
        output
            .lines()
            .map(|line| {
                let (commit_sha, name) = line.split_once('\t').ok_or_else(|| {
                    io::Error::new(io::ErrorKind::InvalidData, "Invalid Git reference output")
                })?;
                Ok(GitRef {
                    commit_sha: commit_sha.to_owned(),
                    name: name.to_owned(),
                })
            })
            .collect()
    }

    fn command(&self) -> Command {
        let mut command = Command::new("git");
        for (name, _) in std::env::vars_os() {
            if name.to_string_lossy().starts_with("GIT_") {
                command.env_remove(name);
            }
        }
        command
            .args([
                "-c",
                "core.hooksPath=/dev/null",
                "-c",
                "protocol.ext.allow=never",
            ])
            .env("GIT_CONFIG_NOSYSTEM", "1")
            .env("GIT_CONFIG_GLOBAL", "/dev/null")
            .env("GIT_TERMINAL_PROMPT", "0")
            .env(
                "GIT_SSH_COMMAND",
                shell_quote(
                    &Path::new(env!("CARGO_MANIFEST_DIR"))
                        .join("../git-server/scripts/ssh_client.sh"),
                ),
            )
            .env("GIT_SSH_VARIANT", "ssh")
            .env(
                "FL_GIT_SSH_PRIVATE_KEY",
                &self.ssh_identity.private_key_path,
            )
            .env(
                "FL_GIT_SSH_KNOWN_HOSTS",
                &self.ssh_identity.known_hosts_path,
            )
            .kill_on_drop(true);
        command
    }

    #[cfg(test)]
    pub(crate) fn test_config() -> Self {
        Self {
            ssh_identity: SshIdentity {
                private_key_path: PathBuf::from("/unused/id_ed25519"),
                known_hosts_path: PathBuf::from("/unused/known_hosts"),
            },
            repository_root: PathBuf::from("/unused/projects"),
            port: 2222,
            repository_locks: Arc::new(Mutex::new(HashMap::new())),
        }
    }
}

fn validate_project_id(project_id: i32) -> io::Result<()> {
    if project_id <= 0 {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "Project ID must be positive",
        ));
    }
    Ok(())
}

fn shell_quote(path: &Path) -> String {
    format!("'{}'", path.to_string_lossy().replace('\'', "'\\''"))
}

fn reject_symlinks(path: &Path) -> io::Result<()> {
    for ancestor in path.ancestors() {
        match ancestor.symlink_metadata() {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "Git storage and SSH keys must not contain symlinks",
                ));
            }
            Ok(_) => {}
            Err(error) if error.kind() == io::ErrorKind::NotFound => {}
            Err(error) => return Err(error),
        }
    }
    Ok(())
}

async fn run(mut command: Command) -> io::Result<Vec<u8>> {
    let output = tokio::time::timeout(Duration::from_secs(30), command.output())
        .await
        .map_err(|_| io::Error::new(io::ErrorKind::TimedOut, "Git operation timed out"))??;
    if !output.status.success() {
        return Err(io::Error::other(format!(
            "Git operation failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    Ok(output.stdout)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn remote_urls_only_accept_positive_project_ids() {
        let client = GitClient::test_config();
        assert_eq!(
            client.remote_url(7).unwrap(),
            "ssh://git@127.0.0.1:2222/repositories/7.git"
        );
        assert!(client.remote_url(0).is_err());
        assert!(client.remote_url(-1).is_err());
    }

    #[test]
    fn rejects_relative_storage_and_reserved_ports() {
        assert!(GitClient::configured(PathBuf::from("relative/storage"), 2222).is_err());
        assert!(GitClient::configured(PathBuf::from("/tmp/unused"), 22).is_err());
    }

    #[cfg(unix)]
    #[test]
    fn rejects_unsafe_identity_permissions_and_symlink_files() {
        use std::os::unix::fs::{PermissionsExt, symlink};
        let root = std::env::temp_dir().join(format!("fl-git-config-{}", uuid::Uuid::new_v4()));
        let keys = root.join("ssh/client");
        std::fs::create_dir_all(&keys).unwrap();
        std::fs::create_dir(root.join("projects")).unwrap();
        let private_key = keys.join("id_ed25519");
        let hosts = keys.join("known_hosts");
        for file in [&private_key, &hosts] {
            std::fs::write(file, b"configuration fixture").unwrap();
            std::fs::set_permissions(file, std::fs::Permissions::from_mode(0o600)).unwrap();
        }
        assert!(GitClient::configured(root.clone(), 2222).is_ok());
        std::fs::set_permissions(&private_key, std::fs::Permissions::from_mode(0o644)).unwrap();
        assert!(GitClient::configured(root.clone(), 2222).is_err());
        std::fs::set_permissions(&private_key, std::fs::Permissions::from_mode(0o600)).unwrap();
        std::fs::remove_file(&hosts).unwrap();
        symlink(&private_key, &hosts).unwrap();
        assert!(GitClient::configured(root.clone(), 2222).is_err());
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn ssh_wrapper_path_is_quoted_for_git() {
        assert_eq!(
            shell_quote(Path::new("/tmp/project's files/ssh.sh")),
            "'/tmp/project'\\''s files/ssh.sh'"
        );
    }

    #[tokio::test]
    #[ignore = "requires the local Git SSH server and keys prepared by setup"]
    async fn local_ssh_server_supports_snapshots_and_rejects_overwrites() {
        let client = GitClient::from_env().unwrap();
        let project_id = 2_000_000_000 + (uuid::Uuid::new_v4().as_u128() % 100_000_000) as i32;
        let repository = client.repository_root.join(format!("{project_id}.git"));
        assert!(!repository.exists());
        let worktree = std::env::temp_dir().join(format!("fl-git-ssh-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir(&worktree).unwrap();
        let test_worktree = worktree.clone();
        let test_client = client.clone();
        let result = tokio::spawn(async move {
            let created = test_client
                .create_project_repository(project_id)
                .await
                .unwrap();
            assert_eq!(
                test_client
                    .create_project_repository(project_id)
                    .await
                    .unwrap(),
                created
            );
            assert!(
                test_client
                    .list_snapshot_refs(project_id)
                    .await
                    .unwrap()
                    .is_empty()
            );
            let mut init = test_client.command();
            init.args(["init", "--quiet"]).arg(&test_worktree);
            run(init).await.unwrap();
            let content = b"print('exact uploaded source')\n";
            std::fs::write(test_worktree.join("train.py"), content).unwrap();
            let mut add = test_client.command();
            add.arg("-C").arg(&test_worktree).args(["add", "train.py"]);
            run(add).await.unwrap();
            let mut commit = test_client.command();
            commit.arg("-C").arg(&test_worktree).args([
                "-c",
                "user.name=Git test",
                "-c",
                "user.email=test@localhost",
                "commit",
                "--quiet",
                "-m",
                "SSH fixture",
            ]);
            run(commit).await.unwrap();
            let mut head = test_client.command();
            head.arg("-C")
                .arg(&test_worktree)
                .args(["rev-parse", "HEAD"]);
            let commit = String::from_utf8(run(head).await.unwrap()).unwrap();
            let remote = test_client.remote_url(project_id).unwrap();
            let mut push = test_client.command();
            push.arg("-C")
                .arg(&test_worktree)
                .args(["push", &remote, "HEAD:refs/snapshots/test"]);
            run(push).await.unwrap();
            let refs = test_client.list_snapshot_refs(project_id).await.unwrap();
            assert_eq!(
                refs,
                vec![GitRef {
                    commit_sha: commit.trim().to_owned(),
                    name: "refs/snapshots/test".into()
                }]
            );

            // Fetch into a different repository to verify actual object transfer.
            let fetched = test_worktree.join("fetched");
            let mut init = test_client.command();
            init.args(["init", "--quiet"]).arg(&fetched);
            run(init).await.unwrap();
            let mut fetch = test_client.command();
            fetch.arg("-C").arg(&fetched).args([
                "fetch",
                "--quiet",
                &remote,
                "refs/snapshots/test",
            ]);
            run(fetch).await.unwrap();
            let mut show = test_client.command();
            show.arg("-C")
                .arg(&fetched)
                .args(["show", "FETCH_HEAD:train.py"]);
            assert_eq!(run(show).await.unwrap(), content);

            let mut commit = test_client.command();
            commit.arg("-C").arg(&test_worktree).args([
                "-c",
                "user.name=Git test",
                "-c",
                "user.email=test@localhost",
                "commit",
                "--quiet",
                "--allow-empty",
                "-m",
                "Replacement",
            ]);
            run(commit).await.unwrap();
            let mut overwrite = test_client.command();
            overwrite.arg("-C").arg(&test_worktree).args([
                "push",
                &remote,
                "HEAD:refs/snapshots/test",
            ]);
            assert!(
                run(overwrite)
                    .await
                    .unwrap_err()
                    .to_string()
                    .contains("Published snapshot references cannot be changed")
            );
            let mut deletion = test_client.command();
            deletion
                .arg("-C")
                .arg(&test_worktree)
                .args(["push", &remote, ":refs/snapshots/test"]);
            assert!(run(deletion).await.is_err());
            assert_eq!(
                test_client.list_snapshot_refs(project_id).await.unwrap(),
                refs
            );

            let unknown_host = test_worktree.join("unknown_hosts");
            std::fs::write(&unknown_host, b"").unwrap();
            let mut untrusted = test_client.clone();
            untrusted.ssh_identity.known_hosts_path = unknown_host;
            assert!(
                untrusted
                    .list_snapshot_refs(project_id)
                    .await
                    .unwrap_err()
                    .to_string()
                    .contains("Host key verification failed")
            );
            let mut wrong_key = test_client.clone();
            wrong_key.ssh_identity.private_key_path = test_worktree.join("missing_key");
            assert!(wrong_key.list_snapshot_refs(project_id).await.is_err());

            let mut shell = Command::new(
                Path::new(env!("CARGO_MANIFEST_DIR")).join("../git-server/scripts/ssh_client.sh"),
            );
            shell
                .env(
                    "FL_GIT_SSH_PRIVATE_KEY",
                    &test_client.ssh_identity.private_key_path,
                )
                .env(
                    "FL_GIT_SSH_KNOWN_HOSTS",
                    &test_client.ssh_identity.known_hosts_path,
                )
                .args(["-p", &test_client.port.to_string(), "git@127.0.0.1", "id"]);
            assert!(
                run(shell)
                    .await
                    .unwrap_err()
                    .to_string()
                    .contains("Only Git fetch and push are allowed")
            );
        })
        .await;
        if repository.exists() {
            std::fs::remove_dir_all(&repository).unwrap();
        }
        std::fs::remove_dir_all(&worktree).unwrap();
        result.unwrap();
    }
}
